### PR TITLE
Upload status in file list

### LINKED ISSUE #185: Refresh filebrowser list
After a file is uploaded, the filebrowser don't refresh the file list and the use only the the new file after he manual refresh the filelist (pull to refresh)

- add auto refresh after file is uploaded
- show pending upload in file list with the current status

### PR DESCRIPTION
**Pull request by L-Henke**
Adds currently uploading file into the file list with a cloud upload symbol and a spinning progress bar. File list is automatically refreshed after finished or failed upload. Might not be perfectly animated, but should be feasible.

Current uploads are stored in LocalQabelService. Thus the status is independent from the FileFragment life cycle. Pending uploads are redrawn even when you browse to another folder and return to the folder where an upload is currently in progress.

Closes #185, #187

### CODE REVIEW

**Comment by dannywerner** [comment]
iam see only one file that uploading, but iam have add multiple files

**Comment by audax** [comment]
Can we include a test that checks for the notification for multiple uploads?

**Comment by dannywerner** [comment]
the user friendly way is that he see all files that in the pending download list

**Comment by audax** [comment]
Maybe the problem is that the BoxProvider, being a single threaded DocumentProvider, can only see 1 upload at a time. Could that be case?

**Pull request merged**
