### PR TITLE
cleaned icons and re-added them with reasonable namings

### PR DESCRIPTION
**Pull request by mr-gosh**
cleaned icons and re-added them with reasonable namings in white and 80%-black

### CODE REVIEW

**Comment by mr-gosh** [comment]
@audax if you give me a hint which file has the icon mapping inside - i'll have a look, if i can help rearanging is possible for me?!?

**Comment by audax** [comment]
I am not sure if we actually have file with a mapping. Afaik we just use the icons directly so we have to update all the names (should be just the layout xml files) until the code actually compiles.

**Comment by mr-gosh** [comment]
@audax ok - can give me a hint how to test this myself? (you mentioned some kind of script to run the test locally?)

**Comment by mr-gosh** [comment]
@JoGir could you have a look if you can determine why the build is failing?

**Pull request merged**
