### PR TITLE
[WIP] Block-server integration

### PR DESCRIPTION
**Pull request by audax**

### CODE REVIEW

**Comment by wischweh** [comment]
There is still a failing tests, but i think the test is OK and the bug is also reproducable in the actual app
This bug can be reproduced in the app as well as by CreateIdentityTest.addIdentity1Test().

Steps; fresh install of app
1. Create Account
2. Create identity foo following the form
3. Navigate back to Create identity (using the navigation drawer)
4. click "create new identity"
5. press back button without entering something
6. Create identity foo1 following the form
Result: App crashes with the following exception

02-22 11:23:52.785 27699-27699/de.qabel.qabelbox E/AndroidRuntime: FATAL EXCEPTION: main
Process: de.qabel.qabelbox, PID: 27699
java.lang.RuntimeException: Unable to resume activity {de.qabel.qabelbox/de.qabel.qabelbox.activities.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16, result=-1, data=Intent { (has extras) }} to activity {de.qabel.qabelbox/de.qabel.qabelbox.activities.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2774)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16, result=-1, data=Intent { (has extras) }} to activity {de.qabel.qabelbox/de.qabel.qabelbox.activities.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3351)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2761)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
at android.app.ActivityThread.access$800(ActivityThread.java:135) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5001) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.NullPointerException
at de.qabel.qabelbox.activities.MainActivity.addIdentity(MainActivity.java:716)
at de.qabel.qabelbox.activities.MainActivity.onActivityResult(MainActivity.java:137)
at android.app.Activity.dispatchActivityResult(Activity.java:5423)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3347)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2761) 
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
at android.app.ActivityThread.access$800(ActivityThread.java:135) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5001) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
at dalvik.system.NativeStart.main(Native Method)

**Comment by wischweh** [comment]
I have renamed the addIdentity0Test() to clearIdentities() and removed the @Test annotation. Its now only executed in the clearUp() method. 

I am under the impression that now the test fails due to a bug in the code:
- maybe handling of activities and fragments has a problem
- or the CreateIdentityTest does not return data under all circumstances.

Should the bug fixed in this PR or handled as a separate ticket.

**Comment by wischweh** [comment]
fixed the above bugs.

**Comment by audax** [comment]
```
07:10:40 W/RemoteAndroidTest: ShellCommandUnresponsiveException com.android.ddmlib.ShellCommandUnresponsiveException when running tests de.qabel.qabelbox.test on lge-nexus_5x-00a5fccb8980a0a9
07:10:40 I/InstrumentationResultParser: test run failed: 'Failed to receive adb shell test output within 60000 ms. Test may have timed out, or adb connection to device became unresponsive'
2016-02-22 19:10:40 [STRL.testFailed] test=de.qabel.qabelbox.ui.CreateIdentityTest#addIdentity1Test
2016-02-22 19:10:40 [STRL.testFailed] failed Test failed to run to completion. Reason: 'Failed to receive adb shell test output within 60000 ms. Test may have timed out, or adb connection to device became unresponsive'. Check device logcat for details
2016-02-22 19:10:40 [STRL.testEnded] test=de.qabel.qabelbox.ui.CreateIdentityTest#addIdentity1Test
2016-02-22 19:10:40 [STRL.testRunFailed] errorMessage=Failed to receive adb shell test output within 60000 ms. Test may have timed out, or adb connection to device became unresponsive
2016-02-22 19:10:40 [STRL.testRunEnded] elapsedTime=0
```

Any idea how to fix this? Does it hang like this on your device(s)?

**Comment by audax** [comment]
Disable (skip) the crashing test, create a new issue for that and update the PR to master. I want this PR merged asap.

**Pull request merged**
