### PR TITLE
Clear cache

### PR DESCRIPTION
**Pull request by dannywerner**
finalize clear cache functions
#246

### CODE REVIEW

**Comment by jmt85** [comment]
please use spaces instand of tabs,

it is not possible to understood what are the changes

**Comment by julianseeger** [comment]
tabs are currently totally ok. the problem is that even lines whos content hasn't been changed have been switched from spaces to tabs. and that obfuscates the code changes (the ones that matter)

**Comment by jmt85** [comment]
yes, sorry that was not clear enough

**Comment by audax** [comment]
How does this patch ensure that the cache is cleared when the application is swipe closed?

**Comment by dannywerner** [comment]
the app call the clear cache helper after the mainactivity is destroyed, but not if the activity is in pause state.

**Comment by dannywerner** [comment]
@Override
	protected void onDestroy() {
		if (isTaskRoot()) {
			new CacheFileHelper().freeCacheAsynchron(QabelBoxApplication.getInstance().getApplicationContext());
		}
}

**Pull request merged**
