### PR TITLE
Don't spam the index server in tests

### LINKED ISSUE #690: Disable indexUpload in android tests
Enkore reported this index entry. I suspect the CreateIdentityActivity UITests to trigger this upload.
 ```{
    "identity": {
        "alias": "spoon2",
        "public_key": "...",
        "drop_url": "https://drop.qabel.org/..."
    },
    "public_key_verified": true,
    "items": [{
        "action": "create",
        "field": "phone",
        "value": "+49234567890"
    }]
}

### PR DESCRIPTION
**Pull request by audax**
Resolves #690

### CODE REVIEW

**Comment by JoGir** [comment]
Wizard creates identity after enter phone
https://github.com/audax/qabel-android/blob/ea6522b11b9d22314cfec0af75e31134b9c1010b/qabelbox/src/main/java/de/qabel/qabelbox/activities/CreateIdentityActivity.kt#L91

**Comment by audax** [comment]
When is the identity pushed to the index server? Directly?

**Comment by JoGir** [comment]
interactor fires intent with identit_ created action and indexservice handle it

**Comment by audax** [comment]
meh. I just ignore the test for now.

**Pull request merged**
