### PR TITLE
Show dropmessage visualization in contactlist

### PR DESCRIPTION
**Pull request by dannywerner**
add tests for visualization chat messages
bugfixing
refactoring
#24

### CODE REVIEW

**Comment by julianseeger** [comment]
This PR is pretty obfuscated. To cite from the [core contribution guidelines](https://github.com/Qabel/qabel-core/blob/master/CONTRIBUTING.md#misguided-behavior):
> Misguided behavior
You will find code which is not conform to our style (e.g. you will find spaces instead of tabs). Never address style issues in your pull request or commits. Big patch sets just for re-formatting the source code will not help anyone. Try to commit conform code in the future instead and eventually the style will become conform. Of course big refactoring patch sets may still be a good idea after reaching certain milestones but this has to be discussed (e.g. in an issue) beforehand.

**Comment by jmt85** [comment]
please revert the spaces to tabs

**Comment by audax** [comment]
@julianseeger If your style concerns are resolved, you are free to merge this. The PR is fine imho.

**Comment by julianseeger** [comment]
k, styling wasn't wrong, just unfortunate ;)

**Comment by audax** [comment]
Correction: The PR is of course not fine. I didn't see that the build fails...

**Comment by julianseeger** [comment]
```

BUILD SUCCESSFUL

Total time: 4 mins 0.913 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html
+ status=0
+ set -e
+ date +%Y%m%d-%H%M
+ docroot_dir=/var/www/reports/20160329-1108/
+ apk_dir=/var/www/reports/20160329-1108//apks
+ report_dir=/var/www/reports/20160329-1108//reports
+ mkdir -p /var/www/reports/20160329-1108//apks
+ mkdir -p /var/www/reports/20160329-1108//reports
+ cp -r /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/device /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/file /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/image /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/index.html /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/junit-reports /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/logs /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/result.json /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/static /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/test /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/tv.html /var/lib/jenkins/workspace/qabel-android/qabelbox/build/spoon/debug/work /var/www/reports/20160329-1108//reports
+ cp /var/lib/jenkins/workspace/qabel-android/qabelbox/build/outputs/apk/qabelbox-debug-androidTest-unaligned.apk /var/lib/jenkins/workspace/qabel-android/qabelbox/build/outputs/apk/qabelbox-debug-unaligned.apk /var/lib/jenkins/workspace/qabel-android/qabelbox/build/outputs/apk/qabelbox-debug.apk /var/www/reports/20160329-1108//apks
+ set +x
##########################
visit https://jar.prae.me
for test results
##########################
Build step 'Execute shell' marked build as failure
Setting status of b05b4b48ceb2c0bc06c9f15081877d3b5bdd5e1b to FAILURE with url https://jenkins.prae.me/job/qabel-android/499/ and message: 'Build failed
 No test results found.'
Finished: FAILURE
```

**Comment by julianseeger** [comment]
scheduled a rebuild. I think it was green before I accidentally closed this issue and repopened it (what caused a rebuild).

**Comment by jmt85** [comment]
test is broken on jenkins, is it a problem in jenkins or in the code?

**Comment by audax** [comment]
Just a jenkins quirk

**Pull request merged**
