### PR TITLE
Wrap AckAck ResourceActor into a local service

### LINKED ISSUE #120: Wrap the RessourceActor into a service
https://developer.android.com/guide/components/bound-services.html

Currently it lives in the QabelApplication, but since we need access to the "ressources" all over the application and there can only be one RessourceActor, we should just wrap it into a service.

This also helps with mocking our resources in the tests, we can just use a mock-service then.

Needed for #116

### PR DESCRIPTION
**Pull request by audax**
Move the global ResourceActor into a local service that every activity/fragment/content provider can bind themselves to.

Eventually the every interaction with AckAck will be moved into this service which will broadcast changes to the config via intents.

__This removes the password from the application start. The database now uses a constant password.__

The password should be moved to the android KeyStore introduced in 4.3:
https://developer.android.com/about/versions/android-4.3.html#Security

Resolves #120

### CODE REVIEW

**Comment by audax** [comment]
Needed for #126

**Comment by jan-schreib** [comment]
It is a complicated pullrequest, other than my formatting issues and the password thing I don't see anything.

**Comment by audax** [comment]
I'll take a look at the formatting issues. Could you next time please add your comments on the pull request itself and not a singled out commit? It is less convenient to work this way ;)

**Comment by audax** [comment]
It's probably spaces vs. tabs…

**Comment by jan-schreib** [comment]
@audax It was an accident, will not happan again, Sir.

**Comment by audax** [comment]
Closed in favour of #136 which improves the LocalQabelService by removing the ResourceActor completely.

#136 includes these commits.

**Pull request closed without merging**
