### PR TITLE
File menu icons and filefragment improvements

### LINKED ISSUE #385: sharing menu icons and text wrong
change file sharing menue according to the mockup
icons, text and sepperator

### PR DESCRIPTION
**Pull request by JoGir**
fixes #385

### CODE REVIEW

**Comment by JoGir** [comment]
screenshot_2016-04-04-16-26-34

**Comment by audax** [comment]
Please rebase this onto master. The tests are now fixed…

**Comment by audax** [comment]
retest this

**Comment by JoGir** [comment]
waiting for #459 to update some icons

**Comment by JoGir** [comment]
based on #485

**Pull request merged**
