### PR TITLE
fix locale 

### PR DESCRIPTION
**Pull request by dannywerner**
for account and other server communication. with this fix, the app show localizated account response messages like 'passwort zu kurz'.

### CODE REVIEW

**Comment by jasinai** [comment]
What is the purpose of a lowercased `Accept-Language`?

**Comment by audax** [comment]
Indeed, why should that be lower cased?

**Comment by dannywerner** [comment]
some changes in other pr. maybe we can ignore this pr

**Comment by dannywerner** [comment]
already fixed in master branch with other pr from me

**Pull request closed without merging**
